name: shopping_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

#----------------------PACKAGES---------------------------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Icons

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  #
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1


  # product Specific

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  
  uses-material-design: true


  #---------------------------LOCAL ASSETS -------------------#
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/icons/brands/
    - assets/icons/payment_methods/
    - assets/icons/
    - assets/logos/

  #---------------------------LOCAL FONTS -------------------#

